---
permalink: sm-storage/decide-to-use-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: create, volumes, using, either, pool, group, selection, depend, primarily, key, storage, requirements, expect, workload, performance, data, protection 
summary: 풀 또는 볼륨 그룹을 사용하여 볼륨을 생성할 수 있습니다. 최적의 선택은 주로 예상되는 I/O 워크로드, 성능 요구 사항 및 데이터 보호 요구 사항과 같은 주요 스토리지 요구 사항에 따라 달라집니다. 
---
= 풀 또는 볼륨 그룹을 사용할지 여부를 결정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
풀 또는 볼륨 그룹을 사용하여 볼륨을 생성할 수 있습니다. 최적의 선택은 주로 예상되는 I/O 워크로드, 성능 요구 사항 및 데이터 보호 요구 사항과 같은 주요 스토리지 요구 사항에 따라 달라집니다.



== 풀 또는 볼륨 그룹을 선택해야 하는 이유

* 풀을 선택하십시오 *

* 더 빠른 드라이브 리빌드 및 단순화된 스토리지 관리가 필요한 경우, 씬 볼륨 또는 랜덤 워크로드가 필요합니다.
* 풀을 구성하는 드라이브 세트에 각 볼륨의 데이터를 무작위로 분산하려는 경우
+
풀 또는 풀의 볼륨은 RAID 레벨을 설정하거나 변경할 수 없습니다. 풀은 RAID 레벨 6을 사용합니다.



* 볼륨 그룹을 선택합니다 *

* 최대 시스템 대역폭이 필요한 경우 스토리지 설정을 조정할 수 있고 워크로드가 매우 순차적입니다.
* RAID 레벨을 기반으로 드라이브에 데이터를 배포하려는 경우 볼륨 그룹을 생성할 때 RAID 레벨을 지정할 수 있습니다.
* 볼륨 그룹을 구성하는 드라이브 세트를 통해 각 볼륨의 데이터를 순차적으로 쓰려는 경우


[NOTE]
====
풀은 볼륨 그룹과 함께 존재할 수 있으므로 스토리지 어레이에는 풀과 볼륨 그룹이 모두 포함될 수 있습니다.

====


== 풀과 볼륨 그룹 간의 기능 차이

다음 표에서는 볼륨 그룹과 풀을 비교하여 보여 줍니다.

[cols="3*"]
|===
| 사용 | 수영장 | 볼륨 그룹 


 a| 
워크로드 임의
 a| 
더 좋습니다
 a| 
좋습니다



 a| 
순차 워크로드
 a| 
좋습니다
 a| 
더 좋습니다



 a| 
드라이브 리빌드 시간
 a| 
더 빠른 속도
 a| 
느린 속도



 a| 
성능(최적 모드)
 a| 
양호: 소규모 블록, 랜덤 워크로드에 적합
 a| 
좋음: 대규모 블록, 순차적 워크로드에 적합



 a| 
성능(드라이브 리빌드 모드)
 a| 
우수: 일반적으로 RAID 6보다 우수
 a| 
성능 저하: 최대 40% 성능 저하



 a| 
다중 드라이브 장애
 a| 
데이터 보호 향상: 리빌드 속도 향상 및 우선순위 지정
 a| 
데이터 보호 기능 저하: 느린 리빌드, 더 높은 데이터 손실 위험



 a| 
드라이브 추가
 a| 
빠른 속도: 즉석에서 풀에 추가
 a| 
느림: 동적 용량 확장 작업이 필요합니다



 a| 
씬 볼륨이 지원됩니다
 a| 
예
 a| 
아니요



 a| 
SSD(Solid State Disk) 지원
 a| 
예
 a| 
예



 a| 
단순한 관리
 a| 
예: 구성할 핫 스페어 또는 RAID 설정이 없습니다
 a| 
아니요: 핫 스페어를 할당하고 RAID를 구성해야 합니다



 a| 
성능 조정 가능
 a| 
아니요
 a| 
예

|===