---
permalink: sm-storage/how-does-my-selected-workload-impact-volume-creation.html 
sidebar: sidebar 
keywords: workload, storage, object, support, application, define, more, instance, system, manager, configure, contain, volumes, similar, underlying, characteristics, optimized, based, type, support, example, create, server, subsequently, underlying 
summary: 워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 애플리케이션별로 하나 이상의 워크로드 또는 인스턴스를 정의할 수 있습니다. 일부 애플리케이션의 경우 System Manager에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 예를 들어, Microsoft SQL Server 애플리케이션을 지원하는 워크로드를 생성한 다음 해당 워크로드에 대한 볼륨을 생성하는 경우 기본 볼륨 특성은 Microsoft SQL Server를 지원하도록 최적화되어 있습니다. 
---
= 선택한 워크로드가 볼륨 생성에 어떤 영향을 미칩니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 애플리케이션별로 하나 이상의 워크로드 또는 인스턴스를 정의할 수 있습니다. 일부 애플리케이션의 경우 System Manager에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 예를 들어, Microsoft SQL Server 애플리케이션을 지원하는 워크로드를 생성한 다음 해당 워크로드에 대한 볼륨을 생성하는 경우 기본 볼륨 특성은 Microsoft SQL Server를 지원하도록 최적화되어 있습니다.

* * 응용 프로그램별 *. 애플리케이션별 워크로드를 사용하여 볼륨을 생성하는 경우, 애플리케이션 워크로드 I/O와 애플리케이션 인스턴스의 기타 트래픽 간의 경합을 최소화하기 위해 최적화된 볼륨 구성을 권장할 수 있습니다. I/O 유형, 세그먼트 크기, 컨트롤러 소유권, 읽기 및 쓰기 캐시와 같은 볼륨 특성은 자동으로 권장 사항이며 다음과 같은 애플리케이션 유형에 대해 생성되는 워크로드에 최적화되어 있습니다.
+
** Microsoft ® SQL Server ™ 를 참조하십시오
** Microsoft ® Exchange Server ™ 를 참조하십시오
** 비디오 감시 애플리케이션
** VMware ESXi ™ (가상 머신 파일 시스템과 함께 사용할 볼륨용) * 볼륨 추가/편집 * 대화 상자를 사용하여 권장 볼륨 구성을 검토하고 시스템 권장 볼륨 및 특성을 편집, 추가 또는 삭제할 수 있습니다.


* * 기타 * (또는 특정 볼륨 생성을 지원하지 않는 애플리케이션). 다른 워크로드는 볼륨 구성을 사용하며, 특정 애플리케이션과 연결되지 않은 워크로드를 생성하려는 경우 또는 System Manager가 스토리지 어레이에서 사용할 애플리케이션에 대한 내장 최적화를 제공하지 않는 경우 수동으로 지정해야 합니다. 볼륨 추가/편집 * 대화 상자를 사용하여 볼륨 구성을 수동으로 지정해야 합니다.

