---
permalink: sm-storage/what-is-the-default-cluster.html 
sidebar: sidebar 
keywords: default, cluster, system, defined, entity, allow, unassociated, host, bus, adapter, port, identifier, logged, storage, array, gain, access, volumes, assign, physically, installed, particular 
summary: '기본 클러스터는 기본 클러스터에 할당된 모든 볼륨에 대한 액세스 권한을 얻기 위해 스토리지 배열에 로그인한 모든 연결되지 않은 호스트 버스 어댑터(HBA) 호스트 포트 식별자를 허용하는 시스템 정의 엔티티입니다. 연결되지 않은 호스트 포트 식별자는 호스트에 물리적으로 설치되어 있고 스토리지 배열에 로그인한 상태에서 특정 호스트와 논리적으로 연결되지 않는 호스트 포트입니다.' 
---
= 기본 클러스터는 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 클러스터는 기본 클러스터에 할당된 모든 볼륨에 대한 액세스 권한을 얻기 위해 스토리지 배열에 로그인한 모든 연결되지 않은 호스트 버스 어댑터(HBA) 호스트 포트 식별자를 허용하는 시스템 정의 엔티티입니다. 연결되지 않은 호스트 포트 식별자는 호스트에 물리적으로 설치되어 있고 스토리지 배열에 로그인한 상태에서 특정 호스트와 논리적으로 연결되지 않는 호스트 포트입니다.

[NOTE]
====
호스트가 스토리지 배열의 특정 볼륨에 특정 액세스 권한을 가지도록 하려면 기본 클러스터를 _사용하지_않아야 합니다. 대신 호스트 포트 식별자를 해당 호스트에 연결해야 합니다. 이 작업은 호스트 생성 작업 중에 System Manager를 사용하여 수동으로 수행하거나 각 호스트에 설치된 HCA(호스트 컨텍스트 에이전트)를 사용하여 자동으로 수행할 수 있습니다. 그런 다음 개별 호스트 또는 호스트 클러스터에 볼륨을 할당합니다.

====
외부 스토리지 환경이 모든 호스트 및 스토리지 배열에 연결된 모든 로그인 호스트 포트 식별자를 모든 볼륨에 액세스할 수 있도록 허용하는 특수한 상황에서는 _ 전용 _ 기본 클러스터를 사용해야 합니다(모든 액세스 모드). 호스트를 스토리지 어레이 또는 System Manager에 특별히 알려주지 않습니다.

처음에는 CLI(Command Line Interface)를 통해 기본 클러스터에만 볼륨을 할당할 수 있습니다. 하지만 기본 클러스터에 볼륨을 한 개 이상 할당한 후에는 System Manager에 이 개체(기본 클러스터라고 함)가 표시되고 System Manager를 사용하여 이 엔터티를 관리할 수 있습니다.
