---
settings:
  name: SANtricity 11.6
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: SANtricity 소프트웨어
    url: "/e-series-santricity-116"
    version-number: '11.6'
  - name: SANtricity 소프트웨어
    url: "/e-series-santricity"
    version-number: '11.7'
  - name: SANtricity 소프트웨어
    url: "/e-series-santricity-115"
    version-number: '11.5'
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: SANtricity 11.6 문서
    url: "/index.html"
  - title: 시스템 관리자
    entries:
    - section: sm-interface
    - section: sm-storage
    - section: sm-mirroring
    - section: sm-hardware
    - section: sm-settings
    - section: sm-support
  - title: Unified Manager를 참조하십시오
    entries:
    - section: um-admin
    - section: um-manage
    - section: um-certificates
  - title: 법적 고지
    url: "/legal-notices.html"
