---
permalink: sm-hardware/controller-terminology.html 
sidebar: sidebar 
keywords: controller, terms, storage, array 
summary: 컨트롤러 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오. 
---
= 컨트롤러 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오.

[cols="1a,3a"]
|===
| 구성 요소 | 설명 


 a| 
컨트롤러
 a| 
컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 System Manager 기능을 구현합니다.



 a| 
컨트롤러 쉘프
 a| 
컨트롤러 쉘프는 드라이브 세트 및 하나 이상의 컨트롤러 캐니스터를 포함합니다. 컨트롤러 캐니스터에는 컨트롤러, 호스트 인터페이스 카드(HIC) 및 배터리가 들어 있습니다.



 a| 
DHCP를 선택합니다
 a| 
DHCP(Dynamic Host Configuration Protocol)는 IP 주소와 같은 네트워크 구성 매개 변수를 동적으로 배포하기 위해 IP(인터넷 프로토콜) 네트워크에서 사용되는 프로토콜입니다.



 a| 
DNS
 a| 
DNS(Domain Name System)는 인터넷 또는 개인 네트워크에 연결된 장치의 명명 시스템입니다. DNS 서버는 도메인 이름의 디렉터리를 유지 관리하고 이를 IP(인터넷 프로토콜) 주소로 변환합니다.



 a| 
이중 구성
 a| 
Duplex는 스토리지 배열 내의 이중 컨트롤러 모듈 구성입니다. 이중 시스템은 컨트롤러, 논리적 볼륨 경로 및 디스크 경로와 관련하여 완전히 이중화됩니다. 한 컨트롤러에 장애가 발생하면 다른 컨트롤러가 I/O를 인수하여 가용성을 유지합니다. 이중 시스템에는 이중 팬 및 전원 공급 장치가 있습니다.



 a| 
전이중/반이중 연결
 a| 
전이중 및 반이중 모드는 연결 모드를 참조하십시오. 전이중 모드에서는 두 장치가 양방향으로 동시에 통신할 수 있습니다. 반이중 모드에서는 장치가 한 번에 한 방향씩 통신할 수 있습니다(한 장치는 메시지를 보내고 다른 장치는 메시지를 받습니다).



 a| 
HIC
 a| 
HIC(호스트 인터페이스 카드)는 컨트롤러 캐니스터 내에 선택적으로 설치할 수 있습니다. 컨트롤러에 내장된 호스트 포트를 베이스보드 호스트 포트라고 합니다. HIC에 내장된 호스트 포트를 HIC 포트라고 합니다.



 a| 
ICMP ping 응답
 a| 
ICMP(Internet Control Message Protocol)는 네트워크 컴퓨터의 운영 체제에서 메시지를 보내는 데 사용되는 프로토콜입니다. ICMP 메시지는 호스트에 연결할 수 있는지 여부와 해당 호스트와 패킷을 주고 받는 데 걸리는 시간을 결정합니다.



 a| 
MAC 주소
 a| 
MAC 주소(Media Access Control Identifier)는 동일한 물리적 전송 네트워크 인터페이스의 두 포트를 연결하는 별도의 논리 채널을 구분하기 위해 이더넷에서 사용됩니다.



 a| 
관리 클라이언트
 a| 
관리 클라이언트는 System Manager 액세스를 위해 브라우저가 설치된 컴퓨터입니다.



 a| 
MTU
 a| 
MTU(Maximum Transmission Unit)는 네트워크에서 전송할 수 있는 가장 큰 크기의 패킷 또는 프레임입니다.



 a| 
NTP
 a| 
NTP(Network Time Protocol)는 데이터 네트워크의 컴퓨터 시스템 간 클록 동기화를 위한 네트워킹 프로토콜입니다.



 a| 
단일 구성
 a| 
Simplex는 스토리지 어레이 내에서 단일 컨트롤러 모듈 구성입니다. 단일 시스템은 컨트롤러 또는 디스크 경로 이중화를 제공하지 않지만 이중 팬 및 전원 공급 장치가 있습니다.



 a| 
VLAN
 a| 
VLAN(Virtual Local Area Network)은 동일한 디바이스(스위치, 라우터 등)에서 지원하는 다른 네트워크와 물리적으로 분리된 것처럼 작동하는 논리적 네트워크입니다.

|===