---
permalink: sm-hardware/drive-terminology.html 
sidebar: sidebar 
keywords: drive, apply, storage array 
summary: 드라이브 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오. 
---
= 드라이브 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오.

[cols="1a,3a"]
|===
| 구성 요소 | 설명 


 a| 
DA
 a| 
DA(Data Assurance)는 데이터를 컨트롤러를 통해 드라이브로 전송할 때 발생할 수 있는 오류를 확인하고 수정하는 기능입니다. Fibre Channel과 같은 DA 지원 입출력 인터페이스를 사용하는 호스트에서 풀 또는 볼륨 그룹 레벨에서 Data Assurance를 설정할 수 있습니다.



 a| 
드라이브 보안 기능
 a| 
드라이브 보안은 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브를 통해 추가 보안 계층을 제공하는 스토리지 어레이 기능입니다. 이러한 드라이브를 드라이브 보안 기능과 함께 사용하는 경우 데이터에 액세스하려면 보안 키가 필요합니다. 드라이브가 어레이에서 물리적으로 제거되면 다른 어레이에 설치될 때까지 작동할 수 없으며, 이때 올바른 보안 키가 제공될 때까지 보안 잠금 상태가 됩니다.



 a| 
드라이브 쉘프
 a| 
확장 쉘프라고도 하는 드라이브 쉘프에는 드라이브 세트 및 IOXM(입출력 모듈) 2개가 포함됩니다. IOM에는 드라이브 쉘프를 컨트롤러 쉘프 또는 다른 드라이브 쉘프에 연결하는 SAS 포트가 포함되어 있습니다.



 a| 
DULBE
 a| 
DULBE(할당 취소 또는 기록되지 않은 논리적 블록 오류)는 스토리지 어레이가 볼륨의 일부인 블록을 할당 해제할 수 있도록 하는 NVMe 드라이브의 옵션입니다. 드라이브에서 블록을 할당 해제하면 볼륨 초기화에 걸리는 시간을 크게 줄일 수 있습니다. 또한 호스트는 NVMe Dataset Management 명령을 사용하여 볼륨에서 논리적 블록을 할당 해제할 수 있습니다.



 a| 
FDE 드라이브
 a| 
FDE(전체 디스크 암호화) 드라이브는 하드웨어 레벨의 디스크 드라이브에서 암호화를 수행합니다. 하드 드라이브에는 쓰기 중에 데이터를 암호화한 다음 읽기 중에 데이터를 해독하는 ASIC 칩이 포함되어 있습니다.



 a| 
FIPS 드라이브
 a| 
FIPS 드라이브는 FIPS(Federal Information Processing Standards) 140-2 레벨 2를 사용합니다. 이러한 드라이브는 강력한 암호화 알고리즘 및 방법을 보장하는 미국 정부 표준을 준수하는 FDE 드라이브입니다. FIPS 드라이브는 FDE 드라이브보다 보안 표준이 더 높습니다.



 a| 
HDD
 a| 
하드 디스크 드라이브(HDD)는 자기 코팅으로 회전하는 금속 플래터를 사용하는 데이터 저장 장치입니다.



 a| 
핫 스페어 드라이브
 a| 
핫 스페어는 RAID 1, RAID 5 또는 RAID 6 볼륨 그룹의 대기 드라이브 역할을 합니다. 데이터가 없는 완전한 기능을 갖춘 드라이브입니다. 볼륨 그룹에서 드라이브에 장애가 발생하면 컨트롤러는 장애가 발생한 드라이브에서 핫 스페어로 데이터를 자동으로 재구성합니다.



 a| 
NVMe를 참조하십시오
 a| 
NVMe(비휘발성 메모리 익스프레스)는 SSD 드라이브와 같은 플래시 기반 스토리지 장치를 위해 설계된 인터페이스입니다. NVMe는 이전 논리 장치 인터페이스와 비교하여 I/O 오버헤드를 줄이고 성능 개선을 포함합니다.



 a| 
SAS를 참조하십시오
 a| 
SAS(Serial Attached SCSI)는 컨트롤러를 디스크 드라이브에 직접 연결하는 지점 간 직렬 프로토콜입니다.



 a| 
보안 지원 드라이브
 a| 
보안이 가능한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있으며, 이 드라이브는 쓰기 중에 데이터를 암호화하고 읽기 중에 데이터를 해독합니다. 이러한 드라이브는 드라이브 보안 기능을 사용하여 추가 보안을 위해 사용할 수 있으므로 보안 -_가능_으로 간주됩니다. 드라이브 보안 기능이 이러한 드라이브에 사용된 볼륨 그룹 및 풀에 대해 활성화된 경우 드라이브는 secure-_enabled_가 됩니다.



 a| 
보안 지원 드라이브
 a| 
보안 지원 드라이브는 드라이브 보안 기능과 함께 사용됩니다. 드라이브 보안 기능을 활성화한 다음 보안 -_가능_ 드라이브의 풀 또는 볼륨 그룹에 드라이브 보안을 적용하면 드라이브는 보안__- 사용__ 상태가 됩니다. 읽기 및 쓰기 액세스는 올바른 보안 키로 구성된 컨트롤러를 통해서만 사용할 수 있습니다. 이렇게 추가된 보안으로 인해 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스가 방지됩니다.



 a| 
SSD를 지원합니다
 a| 
SSD(Solid-State Disk)는 데이터를 영구적으로 저장하기 위해 솔리드 스테이트 메모리(플래시)를 사용하는 데이터 스토리지 장치입니다. SSD는 기존의 하드 드라이브를 에뮬레이트하며 하드 드라이브에서 사용하는 것과 동일한 인터페이스로 사용할 수 있습니다.

|===