---
permalink: sm-hardware/erase-drive.html 
sidebar: sidebar 
keywords: erase, secure, enabled, drive, reuse, volume, group, pool, ssd cache, storage array 
summary: 다른 볼륨 그룹, 풀, SSD 캐시 또는 다른 스토리지 어레이에서 다시 사용할 수 있도록 보안 지원 드라이브를 지울 수 있습니다. 이 절차는 드라이브의 보안 속성을 재설정하고 데이터를 다시 읽을 수 없도록 합니다. 
---
= 보안 지원 드라이브를 지웁니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다른 볼륨 그룹, 풀, SSD 캐시 또는 다른 스토리지 어레이에서 다시 사용할 수 있도록 보안 지원 드라이브를 지울 수 있습니다. 이 절차는 드라이브의 보안 속성을 재설정하고 데이터를 다시 읽을 수 없도록 합니다.

보안 사용 드라이브가 할당되지 않음 상태여야 합니다.

보안 지원 드라이브의 모든 데이터를 제거하고 드라이브의 보안 속성을 재설정하려는 경우에만 보안 지우기 옵션을 사용하십시오.

[CAUTION]
====
* 데이터 손실 가능성 * -- 보안 지우기 작업은 실행 취소할 수 없습니다. 절차를 진행하는 동안 올바른 드라이브를 선택해야 합니다.

====
.단계
. 하드웨어 * 를 선택합니다.
. 그래픽에 컨트롤러가 표시되면 * 쉘프 전면 표시 * 를 클릭합니다.
+
그래픽이 변경되어 컨트롤러 대신 드라이브가 표시됩니다.

. 필터 필드를 사용하여 쉘프에서 안전한 사용을 위해 할당되지 않은 모든 드라이브를 봅니다. Show drives that are... * 드롭다운 목록에서 * Secure-enabled * 및 * Unassigned * 를 선택합니다.
+
[NOTE]
====
모든 드라이브가 동일한 물리적 속성을 공유하는 경우 * Show drives that are... * filter 필드가 나타나지 않습니다. 모든 드라이브가 동일한 논리 속성을 공유하는 경우 스토리지 배열 * 필터 필드의 * 아무 곳이나 나타나지 않습니다.

쉘프 뷰에는 보안이 설정된 할당되지 않은 드라이브만 표시되며, 나머지는 모두 회색으로 표시됩니다.

====
. 지우려는 보안 지원 드라이브를 선택합니다.
+
[CAUTION]
====
* 데이터 손실 가능성 * -- 올바른 드라이브를 선택했는지 확인하십시오. 보안 지우기 작업을 완료한 후에는 데이터를 복구할 수 없습니다.

====
+
드라이브의 컨텍스트 메뉴가 열립니다.

. Secure Erase * 를 선택합니다.
+
보안 지우기 옵션은 할당되지 않은 보안 지원 드라이브를 선택한 경우에만 나타납니다.

+
[NOTE]
====
NVMe SED 드라이브의 경우 PSID를 제공해야 합니다. PSID는 드라이브 레이블에서 확인할 수 있습니다. 이 기능은 백업 잠금 키가 없는 경우에 필요합니다.

====
. 보안 지우기 드라이브 대화 상자에서 데이터 손실에 대한 중요 정보를 읽습니다.
. 작업을 확인한 다음 * Erase * (지우기 *)를 클릭합니다.


이제 드라이브를 다른 볼륨 그룹 또는 디스크 풀 또는 다른 스토리지 어레이에서 사용할 수 있습니다.
