---
permalink: sm-hardware/hardware-terminology.html 
sidebar: sidebar 
keywords: hardware, terms, apply, storage 
summary: 스토리지 어레이에 하드웨어 조건이 적용되는 방법에 대해 알아보십시오. 
---
= 하드웨어 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 어레이에 하드웨어 조건이 적용되는 방법에 대해 알아보십시오.

[cols="1a,3a"]
|===
| 구성 요소 | 설명 


 a| 
스토리지 시스템
 a| 
스토리지 어레이에는 쉘프, 컨트롤러, 드라이브, 소프트웨어 및 펌웨어가 포함되어 있습니다.



 a| 
쉘프
 a| 
쉘프는 캐비닛 또는 랙에 설치된 엔클로저입니다. 여기에는 스토리지 어레이의 하드웨어 구성 요소가 포함됩니다. 쉘프는 컨트롤러 쉘프와 드라이브 쉘프의 두 가지 유형이 있습니다. 컨트롤러 쉘프는 컨트롤러와 드라이브를 포함합니다. 드라이브 쉘프는 입/출력 모듈(IOM) 및 드라이브를 포함합니다.



 a| 
컨트롤러
 a| 
컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 System Manager 기능을 구현합니다.



 a| 
드라이브
 a| 
드라이브는 물리적 데이터 저장 매체를 제공하는 전자기 기계 장치 또는 솔리드 스테이트 메모리 장치입니다.



 a| 
베이
 a| 
베이는 드라이브 또는 다른 구성 요소가 설치된 쉘프의 슬롯입니다.



 a| 
드라이브 쉘프
 a| 
확장 쉘프라고도 하는 드라이브 쉘프에는 드라이브 세트 및 IOXM(입출력 모듈) 2개가 포함됩니다. IOM에는 드라이브 쉘프를 컨트롤러 쉘프 또는 다른 드라이브 쉘프에 연결하는 SAS 포트가 포함되어 있습니다.

[NOTE]
====
EF600 스토리지 시스템에는 드라이브 쉘프를 사용할 수 없습니다.

====


 a| 
컨트롤러 쉘프
 a| 
컨트롤러 쉘프는 드라이브 세트 및 하나 이상의 컨트롤러 캐니스터를 포함합니다. 컨트롤러 캐니스터에는 컨트롤러, 호스트 인터페이스 카드(HIC) 및 배터리가 들어 있습니다.



 a| 
전원/팬 캐니스터
 a| 
전원/팬 캐니스터는 선반으로 미끄러지는 어셈블리입니다. 여기에는 전원 공급 장치 및 내장형 팬이 포함됩니다.



 a| 
IOM(ESM)
 a| 
IOM은 드라이브 쉘프를 컨트롤러 쉘프에 연결하기 위한 SAS 포트가 포함된 입력/출력 모듈입니다.

[NOTE]
====
EF600 스토리지 시스템에는 드라이브 쉘프를 사용할 수 없습니다.

====
[NOTE]
====
이전 컨트롤러 모델에서 IOM은 환경 서비스 모듈(ESM)이라고 했습니다.

====


 a| 
SFP
 a| 
SFP는 SFP(Small Form-factor Pluggable) 트랜시버입니다.

|===