---
permalink: um-manage/import-autosupport-settings.html 
sidebar: sidebar 
keywords: import, autoSupport, settings, 
summary: 한 스토리지 어레이에서 다른 스토리지 어레이로 AutoSupport 구성을 가져올 수 있습니다. 이 배치 작업은 네트워크에서 여러 어레이를 구성해야 하는 시간을 절약합니다. 
---
= AutoSupport 설정을 가져옵니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
한 스토리지 어레이에서 다른 스토리지 어레이로 AutoSupport 구성을 가져올 수 있습니다. 이 배치 작업은 네트워크에서 여러 어레이를 구성해야 하는 시간을 절약합니다.

.시작하기 전에
* AutoSupport는 소스로 사용할 스토리지 어레이에 대해 SANtricity 시스템 관리자에서 구성됩니다(메뉴: 지원 [지원 센터]).
* 타겟 스토리지 시스템에 대한 기존 구성은 SANtricity System Manager(메뉴: 설정 [시스템 > 스토리지 배열 구성 저장])에서 백업됩니다.


.이 작업에 대해
가져온 설정에는 별도 기능(기본 AutoSupport, AutoSupport OnDemand 및 원격 진단), 유지 관리 창, 제공 방법, 및 발송 일정을 참조하십시오.

.단계
. Manage * 페이지에서 * Import Settings * 를 클릭합니다.
+
설정 가져오기 * 마법사가 열립니다.

. 설정 선택 * 대화 상자에서 * AutoSupport * 를 선택한 후 * 다음 * 을 클릭합니다.
+
소스 스토리지를 선택할 수 있는 대화 상자가 열립니다.

. 소스 선택 * 대화 상자에서 가져올 설정이 있는 배열을 선택하고 * 다음 * 을 클릭합니다.
. Select Targets * (대상 선택 *) 대화 상자에서 새 설정을 수신할 하나 이상의 배열을 선택합니다.
+
[NOTE]
====
8.50 미만의 펌웨어를 사용하는 스토리지 어레이는 선택할 수 없습니다. 또한 Unified Manager가 해당 어레이와 통신할 수 없는 경우(예: 오프라인이거나 인증서, 암호, 네트워킹 문제가 있는 경우) 이 대화 상자에 어레이가 표시되지 않습니다.

====
. 마침 * 을 클릭합니다.
+
Operations * 페이지에는 가져오기 작업의 결과가 표시됩니다. 작업이 실패하면 해당 행을 클릭하여 자세한 정보를 볼 수 있습니다.



.결과
이제 타겟 스토리지 시스템이 소스 스토리지와 동일한 AutoSupport 설정으로 구성됩니다.
