---
permalink: sm-settings/configure-snmp-alerts.html 
sidebar: sidebar 
keywords: configuration, snmp alerts, identification, one server, storage array, snmp traps, community name, ip address 
summary: 'SNMP(Simple Network Management Protocol) 경고를 구성하려면 스토리지 배열의 이벤트 모니터에서 SNMP 트랩을 보낼 수 있는 서버를 하나 이상 식별해야 합니다. 구성에 서버의 커뮤니티 이름과 IP 주소가 필요합니다.' 
---
= SNMP 경고에 대한 커뮤니티 및 대상을 구성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMP(Simple Network Management Protocol) 경고를 구성하려면 스토리지 배열의 이벤트 모니터에서 SNMP 트랩을 보낼 수 있는 서버를 하나 이상 식별해야 합니다. 구성에 서버의 커뮤니티 이름과 IP 주소가 필요합니다.

.시작하기 전에
* 네트워크 서버는 SNMP 서비스 애플리케이션으로 구성되어야 합니다. 이벤트 모니터가 해당 주소로 트랩 메시지를 보낼 수 있도록 이 서버의 네트워크 주소(IPv4 또는 IPv6 주소)가 필요합니다. 둘 이상의 서버를 사용할 수 있습니다(최대 10대의 서버가 허용됨).
* 인쇄 가능한 ASCII 문자만 포함하는 커뮤니티 이름을 만들어야 합니다. 네트워크 서버의 암호 역할을 하는 문자열인 커뮤니티 이름은 일반적으로 네트워크 관리자가 만듭니다. 최대 256개의 커뮤니티를 만들 수 있습니다.
* MIB(Management Information Base) 파일이 SNMP 서비스 응용 프로그램을 사용하여 서버에서 복사 및 컴파일되었습니다. 이 MIB 파일은 모니터링 및 관리되는 데이터를 정의합니다.
+
MIB 파일이 없는 경우 NetApp Support 사이트에서 얻을 수 있습니다.

+
** 로 이동합니다 https://mysupport.netapp.com/site/["NetApp 지원"^].
** Downloads * 를 클릭합니다.
** 소프트웨어 * 를 클릭합니다.
** 관리 소프트웨어(예: SANtricity 시스템 관리자)를 찾은 다음 오른쪽의 * Go! * 를 클릭합니다.
** 최신 버전에서 ** 보기 및 다운로드**를 클릭합니다.
** 페이지 하단의 * 계속 * 을 클릭합니다.
** EULA에 동의합니다.
** SNMP 트랩*에 대한 * MIB 파일이 표시될 때까지 아래로 스크롤한 다음 링크를 클릭하여 파일을 다운로드합니다.




이 작업에서는 트랩 대상에 대한 SNMP 서버를 식별하고 구성을 테스트하는 방법을 설명합니다.

.단계
. 메뉴: 설정 [알림] * 을 선택합니다.
. SNMP * 탭을 선택합니다.
+
커뮤니티가 아직 구성되지 않은 경우 SNMP 탭에 "커뮤니티 구성"이 표시됩니다.

. 커뮤니티 구성 * 을 선택합니다.
+
커뮤니티 구성 * 대화 상자가 열립니다.

. 커뮤니티 이름 * 필드에 네트워크 서버에 대한 커뮤니티 문자열을 하나 이상 입력한 다음 * 저장 * 을 클릭합니다.
+
경고 페이지에 "트랩 대상 추가"가 표시됩니다.

. 트랩 대상 추가 * 를 선택합니다.
+
트랩 대상 추가 * 대화 상자가 열립니다.

. 하나 이상의 트랩 대상을 입력하고 관련 커뮤니티 이름을 선택한 다음 * 추가 * 를 클릭합니다.
+
** * 트랩 대상 * -- SNMP 서비스를 실행하는 서버의 IPv4 또는 IPv6 주소를 입력합니다.
** * 커뮤니티 이름 * -- 드롭다운에서 이 트랩 대상에 대한 커뮤니티 이름을 선택합니다. (커뮤니티 이름을 하나만 정의한 경우 이 필드에 이름이 이미 표시됩니다.)
** * 인증 실패 트랩 전송 * -- 인식되지 않는 커뮤니티 이름으로 인해 SNMP 요청이 거부될 때마다 트랩 대상에 알리려면 이 옵션(확인란)을 선택합니다. 추가 * 를 클릭하면 * 알림 * 페이지의 * SNMP * 탭에 트랩 대상 및 관련 커뮤니티 이름이 나타납니다.


. 트랩이 유효한지 확인하려면 표에서 트랩 대상을 선택한 다음 * Test Trap Destination * 을 클릭하여 구성된 주소로 테스트 트랩을 보냅니다.


이벤트 모니터는 alertable 이벤트가 발생할 때마다 SNMP 트랩을 서버로 전송합니다.
