---
permalink: sm-settings/create-external-security-key.html 
sidebar: sidebar 
keywords: drive security, feature, key management server, external key, secure capable drive, storage array 
summary: 키 관리 서버에서 드라이브 보안 기능을 사용하려면 스토리지 어레이에서 키 관리 서버와 보안 가능 드라이브가 공유하는 외부 키를 만들어야 합니다. 
---
= 외부 보안 키를 만듭니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
키 관리 서버에서 드라이브 보안 기능을 사용하려면 스토리지 어레이에서 키 관리 서버와 보안 가능 드라이브가 공유하는 외부 키를 만들어야 합니다.

.시작하기 전에
* 스토리지에 보안 가능 드라이브가 설치되어 있어야 합니다. 이러한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다.
+
[NOTE]
====
FDE 및 FIPS 드라이브가 모두 스토리지 어레이에 설치된 경우 모두 동일한 보안 키를 공유합니다.

====
* 드라이브 보안 기능을 활성화해야 합니다. 그렇지 않으면 이 작업 중에 * 보안 키 생성 불가 * 대화 상자가 열립니다. 필요한 경우 스토리지 공급업체에 드라이브 보안 기능 활성화에 대한 지침을 문의하십시오.
* 로컬 호스트에서 클라이언트 및 서버 인증서를 사용할 수 있으므로 스토리지 시스템 및 키 관리 서버가 서로를 인증할 수 있습니다. 클라이언트 인증서는 컨트롤러의 유효성을 검사하는 반면 서버 인증서는 키 관리 서버의 유효성을 검사합니다.


.이 작업에 대해
이 작업에서는 키 관리 서버의 IP 주소와 사용하는 포트 번호를 정의한 다음 외부 키 관리를 위해 인증서를 로드합니다.

.단계
. 메뉴: 설정 [시스템] * 을 선택합니다.
. 보안 키 관리 * 에서 * 외부 키 생성 * 을 선택합니다.
+
[NOTE]
====
현재 내부 키 관리가 구성되어 있으면 대화 상자가 열리고 외부 키 관리로 전환할지 확인하는 메시지가 표시됩니다.

====
+
외부 보안 키 만들기 * 대화 상자가 열립니다.

. 키 서버에 연결 * 에서 다음 필드에 정보를 입력합니다.
+
** * 키 관리 서버 주소 * -- 키 관리에 사용되는 서버의 정규화된 도메인 이름 또는 IP 주소(IPv4 또는 IPv6)를 입력합니다.
** * 키 관리 포트 번호 * -- KMIP(Key Management Interoperability Protocol) 통신에 사용되는 포트 번호를 입력합니다. 키 관리 서버 통신에 사용되는 가장 일반적인 포트 번호는 5696입니다.
** * 클라이언트 인증서 선택 * -- 첫 번째 * 찾아보기 * 버튼을 클릭하여 스토리지 배열 컨트롤러의 인증서 파일을 선택합니다.
** * 키 관리 서버의 서버 인증서 선택 * -- 두 번째 * 찾아보기 * 버튼을 클릭하여 키 관리 서버의 인증서 파일을 선택합니다.


. 다음 * 을 클릭합니다.
. 생성/백업 키 * 에서 다음 필드에 정보를 입력합니다.
+
** * 암호문 정의/암호문 다시 입력 * -- 암호문을 입력하고 확인합니다. 값은 8자에서 32자 사이여야 하며 다음 각 문자를 포함해야 합니다.
+
*** 대문자(하나 이상) 암호는 대/소문자를 구분합니다.
*** 숫자(하나 이상)
*** !, *, @(하나 이상)와 같은 영숫자 이외의 문자입니다.




+
[CAUTION]
====
나중에 사용할 수 있도록 항목을 기록해 두십시오. 스토리지 어레이에서 보안 지원 드라이브를 이동해야 하는 경우, 드라이브 데이터를 잠금 해제하려면 암호를 알아야 합니다.

====
. 마침 * 을 클릭합니다.
+
입력한 자격 증명을 사용하여 시스템이 키 관리 서버에 연결됩니다. 그런 다음 보안 키의 복사본이 로컬 시스템에 저장됩니다.

+
[NOTE]
====
다운로드한 파일의 경로는 브라우저의 기본 다운로드 위치에 따라 다를 수 있습니다.

====
. 다운로드한 키 파일의 위치와 암호를 기록한 다음 * 닫기 * 를 클릭합니다.
+
외부 키 관리를 위한 추가 링크가 포함된 다음 메시지가 페이지에 표시됩니다.

+
현재 키 관리 방식: 외부

. 테스트 통신 * 을 선택하여 스토리지 어레이와 키 관리 서버 간의 연결을 테스트합니다.
+
대화 상자에 검사 결과가 표시됩니다.



.결과
외부 키 관리를 사용하도록 설정하면 보안 설정된 볼륨 그룹 또는 풀을 생성하거나 기존 볼륨 그룹 및 풀에 대한 보안을 설정할 수 있습니다.

[NOTE]
====
드라이브 전원을 껐다가 다시 켤 때마다 모든 보안 지원 드라이브는 보안 잠금 상태로 변경됩니다. 이 상태에서는 드라이브 초기화 중에 컨트롤러가 올바른 보안 키를 적용할 때까지 데이터에 액세스할 수 없습니다. 잠긴 드라이브를 물리적으로 제거하고 다른 시스템에 설치하는 경우 보안 잠금 상태는 데이터에 대한 무단 액세스를 방지합니다.

====
.작업을 마친 후
* 키 파일이 손상되지 않도록 보안 키의 유효성을 검사해야 합니다.

