---
permalink: sm-settings/unlock-drives-using-an-internal-security-key.html 
sidebar: sidebar 
keywords: secure, enable, storage array, appropriate, importing, new storage, drive 
summary: 보안 설정 드라이브를 한 스토리지 어레이에서 다른 스토리지 어레이로 이동하는 경우 적절한 보안 키를 새 스토리지 어레이로 가져와야 합니다. 키를 가져오면 드라이브의 데이터가 잠금 해제됩니다. 
---
= 보안 키를 사용하여 드라이브 잠금을 해제합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보안 설정 드라이브를 한 스토리지 어레이에서 다른 스토리지 어레이로 이동하는 경우 적절한 보안 키를 새 스토리지 어레이로 가져와야 합니다. 키를 가져오면 드라이브의 데이터가 잠금 해제됩니다.

.시작하기 전에
* 드라이브를 이동하는 대상 스토리지 어레이에 이미 보안 키가 구성되어 있어야 합니다. 마이그레이션된 드라이브는 대상 스토리지 배열에 다시 연결됩니다.
* 잠금을 해제할 드라이브와 연결된 보안 키를 알아야 합니다.
* 보안 키 파일은 관리 클라이언트(System Manager 액세스에 사용되는 브라우저가 있는 시스템)에서 사용할 수 있습니다. 드라이브를 다른 시스템에서 관리하는 스토리지 어레이로 이동하는 경우 보안 키 파일을 해당 관리 클라이언트로 이동해야 합니다.


.이 작업에 대해
이 작업은 스토리지 어레이에서 제거한 후 다른 스토리지 배열에 다시 설치한 보안 지원 드라이브에서 데이터의 잠금을 해제하는 방법을 설명합니다. 어레이가 드라이브를 검색하면 재배치된 드라이브에 대해 "Security Key Needed" 상태와 함께 "Needs Attention" 상태가 표시됩니다. 스토리지 배열에 보안 키를 가져와 드라이브 데이터의 잠금을 해제할 수 있습니다. 이 프로세스 중에 보안 키 파일을 선택하고 키에 대한 암호를 입력합니다.

[NOTE]
====
암호 구문이 스토리지 배열의 관리자 암호와 같지 않습니다.

====
다른 보안 지원 드라이브가 새 스토리지 배열에 설치되어 있는 경우 가져오는 것과 다른 보안 키를 사용할 수 있습니다. 가져오기 프로세스 중에 이전 보안 키는 설치 중인 드라이브의 데이터 잠금을 해제하는 데만 사용됩니다. 잠금 해제 프로세스가 성공하면 새로 설치된 드라이브가 대상 스토리지 배열의 보안 키에 다시 입력됩니다.

.단계
. 설정 [시스템] 메뉴를 선택합니다.
. 보안 키 관리 * 에서 * 보안 드라이브 잠금 해제 * 를 선택합니다.
+
보안 드라이브 잠금 해제 대화 상자가 열립니다. 보안 키가 필요한 모든 드라이브가 표에 나와 있습니다.

. * 선택 사항: * 드라이브 번호 위로 마우스를 가져가면 드라이브 위치(쉘프 번호 및 베이 번호)가 표시됩니다.
. 찾아보기 * 를 클릭한 다음 잠금을 해제할 드라이브에 해당하는 보안 키 파일을 선택합니다.
+
선택한 키 파일이 대화 상자에 나타납니다.

. 이 키 파일과 관련된 암호를 입력합니다.
+
입력한 문자는 마스크됩니다.

. 잠금 해제 * 를 클릭합니다.
+
잠금 해제 작업이 성공하면 대화 상자에 "연결된 보안 드라이브가 잠금 해제되었습니다."라는 메시지가 표시됩니다.



.결과
모든 드라이브가 잠겼다가 잠금 해제되면 스토리지 배열의 각 컨트롤러가 재부팅됩니다. 그러나 대상 스토리지 배열에 이미 일부 잠금 해제된 드라이브가 있는 경우 컨트롤러는 재부팅되지 않습니다.
