---
permalink: sm-support/drive-firmware-upgrades.html 
sidebar: sidebar 
keywords: drive, firmware, control, low, level, operating, characteristics, periodically, manufacturer, release, update, add, new, features, improve, performance, fix, detects 
summary: 드라이브 펌웨어는 드라이브의 낮은 수준의 작동 특성을 제어합니다. 드라이브 제조업체는 주기적으로 드라이브 펌웨어의 업데이트를 릴리스하여 새로운 기능을 추가하고 성능을 개선하며 결함을 수정합니다. 
---
= 드라이브 펌웨어의 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브 펌웨어는 드라이브의 낮은 수준의 작동 특성을 제어합니다. 드라이브 제조업체는 주기적으로 드라이브 펌웨어의 업데이트를 릴리스하여 새로운 기능을 추가하고 성능을 개선하며 결함을 수정합니다.



== 드라이브 펌웨어의 온라인 및 오프라인 업그레이드

드라이브 펌웨어의 업그레이드 방법에는 온라인 및 오프라인 두 가지가 있습니다.



== 온라인

온라인 업그레이드 중에 드라이브는 한 번에 하나씩 순차적으로 업그레이드됩니다. 스토리지 시스템은 업그레이드가 진행되는 동안 입출력을 계속 처리합니다. I/O를 중지할 필요가 없습니다 드라이브에서 온라인 업그레이드를 수행할 수 있는 경우 온라인 방법이 자동으로 사용됩니다.

온라인 업그레이드를 수행할 수 있는 드라이브는 다음과 같습니다.

* 드라이브가 최적의 풀에 있을 때
* 최적의 중복 볼륨 그룹의 드라이브(RAID 1, RAID 5 및 RAID 6)
* 할당되지 않은 드라이브
* 대기 핫 스페어 드라이브


드라이브 펌웨어의 온라인 업그레이드를 수행하는 데 몇 시간이 걸릴 수 있으며, 스토리지 어레이가 잠재적인 볼륨 장애에 노출될 수 있습니다. 다음과 같은 경우 볼륨 장애가 발생할 수 있습니다.

* RAID 1 또는 RAID 5 볼륨 그룹에서 볼륨 그룹의 다른 드라이브가 업그레이드되는 동안 하나의 드라이브에 장애가 발생합니다.
* RAID 6 풀 또는 볼륨 그룹에서 풀 또는 볼륨 그룹의 다른 드라이브가 업그레이드되는 동안 두 개의 드라이브에 장애가 발생합니다.




== 오프라인(병렬)

오프라인 업그레이드 중에 동일한 드라이브 유형의 모든 드라이브가 동시에 업그레이드됩니다. 이 방법을 사용하려면 선택한 드라이브와 연결된 볼륨에 대한 I/O 작업을 중단해야 합니다. 여러 드라이브를 동시에 업그레이드할 수 있으므로(병렬로) 전체 다운타임이 크게 줄어듭니다. 드라이브에서 오프라인 업그레이드만 수행할 수 있는 경우 오프라인 방법이 자동으로 사용됩니다.

다음 드라이브는 오프라인 방법을 사용해야 합니다.

* 비중복 볼륨 그룹의 드라이브(RAID 0)
* 최적화되지 않은 풀 또는 볼륨 그룹의 드라이브입니다
* SSD 캐시 내 드라이브




== 호환성

각 드라이브 펌웨어 파일에는 펌웨어가 실행되는 드라이브 유형에 대한 정보가 들어 있습니다. 지정된 펌웨어 파일은 호환되는 드라이브에만 다운로드할 수 있습니다. System Manager는 업그레이드 프로세스 중에 호환성을 자동으로 확인합니다.
