---
permalink: um-certificates/use-ca-signed-certificate-um.html 
sidebar: sidebar 
keywords: ca certificate, secure, access, management, system, unified manager 
summary: Unified Manager를 호스팅하는 관리 시스템에 안전하게 액세스하기 위해 CA 서명 인증서를 받아서 가져올 수 있습니다. 
---
= CA 서명 인증서를 사용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 호스팅하는 관리 시스템에 안전하게 액세스하기 위해 CA 서명 인증서를 받아서 가져올 수 있습니다.

.시작하기 전에
* 보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다. 그렇지 않으면 인증서 기능이 나타나지 않습니다.


.이 작업에 대해
CA 서명 인증서를 사용하는 것은 2단계 절차입니다.



== 1단계: CSR을 작성하여 제출합니다

먼저 CSR(인증서 서명 요청) 파일을 생성하여 CA로 전송해야 합니다.

.시작하기 전에
* 보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다. 그렇지 않으면 인증서 기능이 나타나지 않습니다.


.이 작업에 대해
이 작업에서는 Unified Manager 및 웹 서비스 프록시를 호스팅하는 시스템에 대해 서명된 관리 인증서를 받기 위해 CA로 보내는 CSR 파일을 생성하는 방법에 대해 설명합니다. 조직에 대한 정보와 호스트 시스템의 IP 주소 또는 DNS 이름을 제공해야 합니다.

[CAUTION]
====
CA에 제출한 후 새 CSR을 생성하지 마십시오. CSR을 생성하면 시스템에서 개인 키 및 공개 키 쌍을 생성합니다. 공개 키는 CSR의 일부이며 개인 키는 키 저장소에 보관됩니다. 서명된 인증서를 받은 후 키 저장소로 가져오면 시스템에서는 개인 키와 공개 키가 모두 원래 쌍이 되도록 합니다. 따라서 CA에 CSR을 제출한 후 새 CSR을 생성해서는 안 됩니다. 이렇게 하면 컨트롤러가 새 키를 생성하고 CA로부터 받은 인증서는 작동하지 않습니다.

====
.단계
. 인증서 관리 * 를 선택합니다.
. 관리 * 탭에서 * CSR 완료 * 를 선택합니다.
. 다음 정보를 입력하고 * 다음 * 을 클릭합니다.
+
** * 조직 * -- 회사 또는 조직의 전체 법적 이름. Inc. 또는 Corp.와 같은 접미사를 포함합니다
** * 조직 단위(선택 사항) * -- 인증서를 처리하는 조직의 사업부입니다.
** * 시/군/구 * -- 호스트 시스템이나 업무가 위치한 도시.
** * 주/지역(선택 사항) * -- 호스트 시스템 또는 비즈니스가 위치한 주 또는 지역입니다.
** * 국가 ISO 코드 * -- 미국 등 해당 국가의 2자리 ISO(International Organization for Standardization) 코드입니다.


. 호스트 시스템에 대한 다음 정보를 입력합니다.
+
** * 공통 이름 * -- 웹 서비스 프록시가 설치된 호스트 시스템의 IP 주소 또는 DNS 이름입니다. 주소가 올바른지 확인합니다. 입력한 주소와 정확하게 일치해야 브라우저에서 Unified Manager에 액세스할 수 있습니다. http:// 또는 https://를 포함하지 마십시오.
** * 대체 IP 주소 * -- 공통 이름이 IP 주소인 경우 호스트 시스템에 대한 추가 IP 주소 또는 별칭을 선택적으로 입력할 수 있습니다. 여러 항목의 경우 쉼표로 구분된 형식을 사용합니다.
** * 대체 DNS 이름 * -- 공통 이름이 DNS 이름이면 호스트 시스템에 대한 추가 DNS 이름을 입력합니다. 여러 항목의 경우 쉼표로 구분된 형식을 사용합니다. 대체 DNS 이름이 없지만 첫 번째 필드에 DNS 이름을 입력한 경우 여기에 해당 이름을 복사합니다.


. 마침 * 을 클릭합니다.
+
CSR 파일이 로컬 시스템에 다운로드됩니다. 다운로드의 폴더 위치는 브라우저에 따라 다릅니다.

. CSR 파일을 CA에 제출하고 서명된 인증서를 PEM 또는 DER 형식으로 요청합니다.


.작업을 마친 후
CA가 인증서 파일을 반환할 때까지 기다린 다음 로 이동합니다 link:step-3-import-management-certificates-unified.html["2단계: 관리 인증서를 가져옵니다"].



== 2단계: 관리 인증서를 가져옵니다

서명된 인증서를 받은 후 Unified Manager 인터페이스가 설치된 호스트 시스템의 인증서 체인을 가져옵니다.

.시작하기 전에
* 보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다. 그렇지 않으면 인증서 기능이 나타나지 않습니다.
* 인증서 서명 요청(.csr 파일)을 생성하여 CA로 보냈습니다.
* CA가 신뢰할 수 있는 인증서 파일을 반환했습니다.
* 인증서 파일이 로컬 시스템에 설치됩니다.
* CA에서 체인 인증서(예: .p7b 파일)를 제공한 경우, 루트 인증서, 하나 이상의 중간 인증서 및 서버 인증서 등 개별 파일에 체인 파일의 압축을 풀어야 합니다. Windows 'certmgr' 유틸리티를 사용하여 파일의 압축을 풀 수 있습니다(마우스 오른쪽 버튼을 클릭하고 * MENU: 모든 작업 [내보내기] * 선택). 내보내기가 완료되면 체인의 각 인증서 파일에 대해 CER 파일이 표시됩니다.


.단계
. 인증서 관리 * 를 선택합니다.
. 관리 * 탭에서 * 가져오기 * 를 선택합니다.
+
인증서 파일을 가져올 수 있는 대화 상자가 열립니다.

. 먼저 루트 및 중간 파일을 선택하고 서버 인증서를 선택하려면 * 찾아보기 * 를 클릭합니다.
+
대화 상자에 파일 이름이 표시됩니다.

. 가져오기 * 를 클릭합니다.


.결과
파일이 업로드되고 검증됩니다. 인증서 정보가 인증서 관리 페이지에 표시됩니다.
